# Blockhouse Work Trial Task - ML Researcher

In [1]:
#imports
import numpy as np
import pandas as pd

In [2]:
data1 = pd.read_csv('data/AAPL_Quotes_Data.csv')
data1.head(10)

,timestamp,bid_price_1,bid_price_2,bid_price_3,bid_price_4,bid_price_5,bid_size_1,bid_size_2,bid_size_3,bid_size_4,...,ask_price_1,ask_price_2,ask_price_3,ask_price_4,ask_price_5,ask_size_1,ask_size_2,ask_size_3,ask_size_4,ask_size_5
0,2024-07-01 13:30:00+00:00,212.51,212.51,212.51,212.51,212.51,120.0,100.0,120.0,220.0,...,211.93,211.93,211.93,211.93,211.93,100.0,200.0,100.0,200.0,300.0
1,2024-07-01 13:31:00+00:00,213.07,213.07,213.07,213.07,213.07,301.0,500.0,600.0,600.0,...,212.35,212.35,212.36,212.36,212.36,200.0,100.0,105.0,205.0,205.0
2,2024-07-01 13:32:00+00:00,213.05,213.05,213.05,213.05,213.05,100.0,100.0,34.0,300.0,...,212.62,212.62,212.64,212.64,212.64,49.0,49.0,100.0,100.0,100.0
3,2024-07-01 13:33:00+00:00,213.25,213.25,213.25,213.25,213.25,100.0,100.0,52.0,110.0,...,212.55,212.55,212.58,212.58,212.58,3195.0,3195.0,251.0,151.0,100.0
4,2024-07-01 13:34:00+00:00,213.47,213.46,213.46,213.46,213.46,20.0,20.0,20.0,20.0,...,213.12,213.12,213.12,213.12,213.12,1.0,1.0,1.0,1.0,1.0
5,2024-07-01 13:35:00+00:00,213.69,213.69,213.69,213.69,213.68,100.0,100.0,110.0,10.0,...,213.33,213.33,213.34,213.34,213.34,10.0,20.0,100.0,101.0,100.0
6,2024-07-01 13:36:00+00:00,214.02,214.02,214.02,214.02,214.02,220.0,220.0,120.0,120.0,...,213.65,213.65,213.65,213.65,213.65,100.0,200.0,510.0,510.0,510.0
7,2024-07-01 13:37:00+00:00,213.97,213.97,213.97,213.97,213.97,200.0,704.0,704.0,208.0,...,213.16,213.16,213.16,213.16,213.16,13.0,13.0,13.0,13.0,45.0
8,2024-07-01 13:38:00+00:00,213.80,213.80,213.80,213.80,213.80,110.0,110.0,210.0,210.0,...,213.25,213.25,213.25,213.25,213.25,200.0,300.0,200.0,110.0,100.0
9,2024-07-01 13:39:00+00:00,213.60,213.60,213.59,213.59,213.59,100.0,110.0,220.0,220.0,...,213.19,213.19,213.19,213.19,213.19,70.0,70.0,100.0,20.0,120.0

In [3]:
data = pd.read_csv('data/merged_bid_ask_ohlcv_data.csv')
data.head(10)

,timestamp,bid_price_1,bid_price_2,bid_price_3,bid_price_4,bid_price_5,bid_size_1,bid_size_2,bid_size_3,bid_size_4,...,publisher_id,instrument_id,open,high,low,close,volume,symbol,log_return,volatility
0,2023-09-12 13:30:00+00:00,179.66,179.66,179.66,179.66,179.66,27600.0,30000.0,23100.0,23100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-09-12 13:31:00+00:00,179.89,179.89,179.89,179.89,179.89,21200.0,900.0,1200.0,20300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-09-12 13:32:00+00:00,180.12,180.12,180.12,180.12,180.11,10000.0,30000.0,20000.0,30000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-09-12 13:33:00+00:00,179.99,179.99,179.99,179.99,179.99,17400.0,19700.0,9700.0,19700.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-09-12 13:34:00+00:00,179.78,179.78,179.78,179.78,179.78,10000.0,10000.0,12100.0,10600.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2023-09-12 13:35:00+00:00,179.84,179.84,179.84,179.84,179.83,300.0,1300.0,1000.0,1300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023-09-12 13:36:00+00:00,179.84,179.84,179.84,179.84,179.84,31700.0,6800.0,31700.0,31700.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2023-09-12 13:37:00+00:00,179.79,179.79,179.79,179.79,179.79,13400.0,300.0,3400.0,13400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2023-09-12 13:38:00+00:00,179.75,179.75,179.75,179.75,179.75,29000.0,36900.0,20000.0,20000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2023-09-12 13:39:00+00:00,179.61,179.61,179.61,179.61,179.61,26200.0,2000.0,22500.0,2500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100964 entries, 0 to 100963
Data columns (total 32 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   timestamp      100964 non-null  object
 1   bid_price_1    100964 non-null  float64
 2   bid_price_2    100931 non-null  float64
 3   bid_price_3    100879 non-null  float64
 4   bid_price_4    100825 non-null  float64
 5   bid_price_5    100769 non-null  float64
 6   bid_size_1     100964 non-null  float64
 7   bid_size_2     100931 non-null  float64
 8   bid_size_3     100879 non-null  float64
 9   bid_size_4     100825 non-null  float64
 10  bid_size_5     100769 non-null  float64
 11  ask_price_1    100964 non-null  float64
 12  ask_price_2    100931 non-null  float64
 13  ask_price_3    100879 non-null  float64
 14  ask_price_4    100825 non-null  float64
 15  ask_price_5    100769 non-null  float64
 16  ask_size_1     100964 non-null  float64
 17  ask_size_2     100931 non-null  float64
 18  ask_size_3     100879 non-null  float64
 19  ask_size_4     100825 non-null  float64
 20  ask_size_5     100769 non-null  float64
 21  rtype          100807 non-null  float64
 22  publisher_id   100807 non-null  float64
 23  instrument_id  100807 non-null  float64
 24  open           100807 non-null  float64
 25  high           100807 non-null  float64
 26  low            100807 non-null  float64
 27  close          100807 non-null  float64
 28  volume         100807 non-null  float64
 29  symbol         100807 non-null  object
 30  log_return     100807 non-null  float64
 31  volatility     100807 non-null  float64
dtypes: float64(30), object(2)
memory usage: 24.6+ MB

In [5]:
#need to change the data type of the timestamp column to be recognized as a date and time
data['timestamp'] = pd.to_datetime(data['timestamp'])
data['timestamp'].dt.date.value_counts()

2023-12-26    390
2023-12-27    390
2024-03-15    390
2024-01-09    390
2024-02-01    390
             ...
2024-02-14    389
2023-11-27    389
2023-12-29    389
2023-11-24    376
2024-07-03    361
Name: timestamp, Length: 259, dtype: int64

In [6]:
print(min(data1['timestamp']), max(data1['timestamp']))

2024-07-01 13:30:00+00:00 2024-08-30 19:59:00+00:00

In [7]:
data24 = data[(data['timestamp']>='2024-07-01 13:30:00+00:00')&(data['timestamp']<'2024-08-30 19:59:00+00:00')]
data24.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17130 entries, 78373 to 95502
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      17130 non-null  datetime64[ns, UTC]
 1   bid_price_1    17130 non-null  float64
 2   bid_price_2    17120 non-null  float64
 3   bid_price_3    17101 non-null  float64
 4   bid_price_4    17083 non-null  float64
 5   bid_price_5    17065 non-null  float64
 6   bid_size_1     17130 non-null  float64
 7   bid_size_2     17120 non-null  float64
 8   bid_size_3     17101 non-null  float64
 9   bid_size_4     17083 non-null  float64
 10  bid_size_5     17065 non-null  float64
 11  ask_price_1    17130 non-null  float64
 12  ask_price_2    17120 non-null  float64
 13  ask_price_3    17101 non-null  float64
 14  ask_price_4    17083 non-null  float64
 15  ask_price_5    17065 non-null  float64
 16  ask_size_1     17130 non-null  float64
 17  ask_size_2     17120 non-null  float64
 18  ask_size_3     17101 non-null  float64
 19  ask_size_4     17083 non-null  float64
 20  ask_size_5     17065 non-null  float64
 21  rtype          17093 non-null  float64
 22  publisher_id   17093 non-null  float64
 23  instrument_id  17093 non-null  float64
 24  open           17093 non-null  float64
 25  high           17093 non-null  float64
 26  low            17093 non-null  float64
 27  close          17093 non-null  float64
 28  volume         17093 non-null  float64
 29  symbol         17093 non-null  object
 30  log_return     17093 non-null  float64
 31  volatility     17093 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(30), object(1)
memory usage: 4.3+ MB

In [8]:
data24['symbol'].unique()

array(['AAPL', nan], dtype=object)

In [9]:
data_aapl = data24[data24['symbol'].notna()]

In [10]:
data_aapl = data_aapl.drop(columns=['rtype', 'publisher_id', 'instrument_id', 'log_return'])

In [11]:
data_aapl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17093 entries, 78373 to 95502
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    17093 non-null  datetime64[ns, UTC]
 1   bid_price_1  17093 non-null  float64
 2   bid_price_2  17093 non-null  float64
 3   bid_price_3  17085 non-null  float64
 4   bid_price_4  17077 non-null  float64
 5   bid_price_5  17063 non-null  float64
 6   bid_size_1   17093 non-null  float64
 7   bid_size_2   17093 non-null  float64
 8   bid_size_3   17085 non-null  float64
 9   bid_size_4   17077 non-null  float64
 10  bid_size_5   17063 non-null  float64
 11  ask_price_1  17093 non-null  float64
 12  ask_price_2  17093 non-null  float64
 13  ask_price_3  17085 non-null  float64
 14  ask_price_4  17077 non-null  float64
 15  ask_price_5  17063 non-null  float64
 16  ask_size_1   17093 non-null  float64
 17  ask_size_2   17093 non-null  float64
 18  ask_size_3   17085 non-null  float64
 19  ask_size_4   17077 non-null  float64
 20  ask_size_5   17063 non-null  float64
 21  open         17093 non-null  float64
 22  high         17093 non-null  float64
 23  low          17093 non-null  float64
 24  close        17093 non-null  float64
 25  volume       17093 non-null  float64
 26  symbol       17093 non-null  object
 27  volatility   17093 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(26), object(1)
memory usage: 3.8+ MB

In [12]:
min(data_aapl['timestamp'])

Timestamp('2024-07-01 13:30:00+0000', tz='UTC')

In [13]:
max(data_aapl['timestamp'])

Timestamp('2024-08-30 19:58:00+0000', tz='UTC')

The data contains information on 17,126 shares, over the course of about two months (7/1/24 through 8/30/24).

The task at hand involves splitting the trades of 1000 shares within one trading day (390 minutes).

The provided features of each quote include the date and time, bid prices 1 through 5, bid sizes 1 through 5, ask prices 1 through 5, and ask sizes 1 through 5.

## Data Processing

In [14]:
# data_aapl['timestamp'].dt.date.value_counts()

Dealing with missing values:

In [15]:
data_aapl['bid_price_5'].isnull().sum()

30

In [16]:
data_aapl['bid_price_4'].isnull().sum()

16

In [17]:
data_aapl['bid_price_3'].isnull().sum()

8

In [18]:
data_aapl['bid_price_2'].isnull().sum()

0

In [19]:
data_aapl['bid_price_1'].isnull().sum()

0

In [20]:
data_aapl['ask_price_5'].isnull().sum()

30

In [21]:
#backfilling values of bid_price 1-5 where there are null values
data_aapl['bid_price_2'] = np.where(~data_aapl['bid_price_1'].isnull(),data_aapl['bid_price_1'],data_aapl['bid_price_2'])
data_aapl['bid_price_3'] = np.where(~data_aapl['bid_price_2'].isnull(),data_aapl['bid_price_2'],data_aapl['bid_price_3'])
data_aapl['bid_price_4'] = np.where(~data_aapl['bid_price_3'].isnull(),data_aapl['bid_price_3'],data_aapl['bid_price_4'])
data_aapl['bid_price_5'] = np.where(~data_aapl['bid_price_4'].isnull(),data_aapl['bid_price_4'],data_aapl['bid_price_5'])

In [22]:
#checking that it worked
data_aapl['bid_price_5'].isnull().sum()

0

In [23]:
#similarly backfilling values for ask_price 1-5 where there are null values
data_aapl['ask_price_2'] = np.where(~data_aapl['ask_price_1'].isnull(),data_aapl['ask_price_1'],data_aapl['ask_price_2'])
data_aapl['ask_price_3'] = np.where(~data_aapl['ask_price_2'].isnull(),data_aapl['ask_price_2'],data_aapl['ask_price_3'])
data_aapl['ask_price_4'] = np.where(~data_aapl['ask_price_3'].isnull(),data_aapl['ask_price_3'],data_aapl['ask_price_4'])
data_aapl['ask_price_5'] = np.where(~data_aapl['ask_price_4'].isnull(),data_aapl['ask_price_4'],data_aapl['ask_price_5'])

In [24]:
data_aapl['ask_price_5'].isnull().sum()

0

Making sure none of the following column values are null:

In [25]:
data_aapl['high'].isnull().sum()

0

In [26]:
data_aapl['low'].isnull().sum()

0

In [27]:
data_aapl['close'].isnull().sum()

0

In [28]:
data_aapl['volume'].isnull().sum()

0

In [29]:
# data['bid_prices_cumsum'] = data.iloc[:,1:6].sum(axis=1)

In [30]:
# data['bid_sizes_cumsum'] = data.iloc[:,6:11].sum(axis=1)

### Baseline Strategies:

The provided function code to obtain the following data values does not work, so I am just calculating them beforehand

In [31]:
# calculating VWAP for each data point, formula from https://medium.com/@financial_python/building-a-vwap-indicator-in-python-81ff9157fb13#:~:text=To%20obtain%20the%20VWAP%20at,VWAP'%20column%20of%20the%20DataFrame.

data_aapl['VWAP'] = (((data_aapl['high'] + data_aapl['low'] + data_aapl['close']) / 3) * data_aapl['volume']).cumsum() / data_aapl['volume'].cumsum()

In [32]:
data_aapl.head()

,timestamp,bid_price_1,bid_price_2,bid_price_3,bid_price_4,bid_price_5,bid_size_1,bid_size_2,bid_size_3,bid_size_4,...,ask_size_4,ask_size_5,open,high,low,close,volume,symbol,volatility,VWAP
78373,2024-07-01 13:30:00+00:00,212.51,212.51,212.51,212.51,212.51,12000.0,22000.0,22000.0,12000.0,...,20000.0,30000.0,212.090,212.520,211.92,212.440,881677.0,AAPL,0.002874,212.293333
78374,2024-07-01 13:31:00+00:00,213.07,213.07,213.07,213.07,213.07,62700.0,60000.0,60100.0,50100.0,...,500.0,10500.0,212.450,213.085,212.35,212.995,173504.0,AAPL,0.003674,212.378289
78375,2024-07-01 13:32:00+00:00,213.05,213.05,213.05,213.05,213.05,67100.0,3400.0,37100.0,37100.0,...,20000.0,10000.0,212.995,213.070,212.61,212.920,81464.0,AAPL,0.003725,212.413291
78376,2024-07-01 13:33:00+00:00,213.25,213.25,213.25,213.25,213.25,11000.0,10000.0,10000.0,15200.0,...,10000.0,10000.0,212.950,213.260,212.55,213.170,68896.0,AAPL,0.003711,212.446440
78377,2024-07-01 13:34:00+00:00,213.47,213.47,213.47,213.47,213.47,2000.0,2000.0,2000.0,2000.0,...,100.0,100.0,213.190,213.480,213.09,213.340,58383.0,AAPL,0.003714,212.486022

In [33]:
# data_aapl['slippage'] = (data_aapl['open'] - data_aapl['VWAP']) * data_aapl['volume'] 
data_aapl['slippage'] = ((data_aapl['close'] - data_aapl['bid_price_1']) / data_aapl['bid_price_1'] )*100
data_aapl['market_impact'] = (4.439584265535017e-06 ) * np.sqrt(data_aapl['volume'])

In [42]:
import pandas as pd
import numpy as np

class Benchmark:
    
    def __init__(self, data):
        """
        Initializes the Benchmark class with provided market data.

        Parameters:
        data (DataFrame): A DataFrame containing market data, including top 5 bid prices and sizes. (Use bid_ask_ohlcv_data)
        """
        # Use data with top 5 bid prices and sizes for benchmarking
        self.data = data

    def get_twap_trades(self, data, initial_inventory, preferred_timeframe=390):
        """
        Generates a trade schedule based on the Time-Weighted Average Price (TWAP) strategy.

        Parameters:
        data (DataFrame): The input data containing timestamps and closing prices for each time step.
        initial_inventory (int): The total number of shares to be sold over the preferred timeframe.
        preferred_timeframe (int): The total number of time steps (default is 390, representing a full trading day).

        Returns:
        DataFrame: A DataFrame containing the TWAP trades with timestamps, price, shares sold, and remaining inventory.
        """
        total_steps = len(data)
        twap_shares_per_step = initial_inventory / preferred_timeframe
        remaining_inventory = initial_inventory
        trades_twap = []
        for step in range(min(total_steps, preferred_timeframe)):
            size_of_slice = min(twap_shares_per_step, remaining_inventory)
            remaining_inventory -= int(np.ceil(size_of_slice))
            trade = {
                'timestamp': data.iloc[step]['timestamp'],
                'step': step,
                'price': data.iloc[step]['close'],
                'initial_price':data.iloc[step]['open'],
                'shares': size_of_slice,
                'inventory': remaining_inventory,
            }
            trades_twap.append(trade)
        return pd.DataFrame(trades_twap)

    def get_vwap_trades(self, data, initial_inventory, preferred_timeframe=390):
        """
        Generates a trade schedule based on the Volume-Weighted Average Price (VWAP) strategy.

        Parameters:
        data (DataFrame): The input data containing timestamps, closing prices, and volumes for each time step.
        initial_inventory (int): The total number of shares to be sold over the preferred timeframe.
        preferred_timeframe (int): The total number of time steps (default is 390, representing a full trading day).

        Returns:
        DataFrame: A DataFrame containing the VWAP trades with timestamps, price, shares sold, and remaining inventory.
        """
        total_volume = data['volume'].sum()
        total_steps = len(data)
        remaining_inventory = initial_inventory
        trades_vwap = []
        for step in range(min(total_steps, preferred_timeframe)):
            volume_at_step = data['volume'].iloc[step]
            size_of_slice = (volume_at_step / total_volume) * initial_inventory
            size_of_slice = min(size_of_slice, remaining_inventory)
            remaining_inventory -= int(np.ceil(size_of_slice))
            trade = {
                'timestamp': data.iloc[step]['timestamp'],
                'step': step,
                'price': data.iloc[step]['close'],
                'initial_price':data.iloc[step]['open'],
                'shares': size_of_slice,
                'inventory': remaining_inventory,
            }
            trades_vwap.append(trade)
        return pd.DataFrame(trades_vwap)

In [43]:
benchmarks = Benchmark(data)
print(benchmarks)

<__main__.Benchmark object at 0x7f9e803eb8b0>

In [44]:
twap_trades = benchmarks.get_twap_trades(data=data_aapl, initial_inventory=1000)

In [45]:
twap_trades

,timestamp,step,price,initial_price,shares,inventory
0,2024-07-01 13:30:00+00:00,0,212.440,212.090,2.564103,997
1,2024-07-01 13:31:00+00:00,1,212.995,212.450,2.564103,994
2,2024-07-01 13:32:00+00:00,2,212.920,212.995,2.564103,991
3,2024-07-01 13:33:00+00:00,3,213.170,212.950,2.564103,988
4,2024-07-01 13:34:00+00:00,4,213.340,213.190,2.564103,985
...,...,...,...,...,...,...
385,2024-07-01 19:55:00+00:00,385,216.950,216.590,0.000000,0
386,2024-07-01 19:56:00+00:00,386,216.855,216.955,0.000000,0
387,2024-07-01 19:57:00+00:00,387,216.930,216.860,0.000000,0
388,2024-07-01 19:58:00+00:00,388,216.775,216.940,0.000000,0
389,2024-07-01 19:59:00+00:00,389,216.730,216.780,0.000000,0

In [49]:
vwap_trades = benchmarks.get_vwap_trades(data=data_aapl, initial_inventory=1000)

In [69]:
class benchmark_sims():
    def __init__(self, trades):
        self.trades = trades
    def components(self, alpha, trades):
        for idx in range(len(trades)):
            actual_price = trades.iloc[idx]['price']
            shares = trades.iloc[idx]['shares']
            Slippage = (trades.iloc[idx]['initial_price'] - trades.iloc[idx]['price']) * shares  # Assumes bid_price is in your dataset
            Market_Impact = alpha * np.sqrt(shares)
            return np.array([Slippage, Market_Impact])
    def simulate_strategy(self, trades, preferred_timeframe):

        # Initialize result lists
        slippage = []
        market_impact = []
        alpha = 4.439584265535017e-06 
        rewards = []
        shares_traded = []

        # Simulate the strategy
        for idx in range(len(trades)):
            shares = trades.iloc[idx]['shares']
            reward = self.components(alpha, trades)
#             reward = np.array([data.iloc[idx]['slippage'], data.iloc[idx]['market_impact']])
            slippage.append(reward[0])
            market_impact.append(reward[1])
            shares_traded.append(shares)
            rewards.append(reward)

        return slippage, market_impact

In [73]:
simulate_benchmark = benchmark_sims(twap_trades)
print(simulate_benchmark)

<__main__.benchmark_sims object at 0x7f9ea8a25a90>

In [74]:
twap_sim = simulate_benchmark.simulate_strategy(twap_trades,  preferred_timeframe=390)

In [78]:
np.shape(twap_sim)

(2, 390)

In [75]:
print("Mean TWAP slippage:", np.mean(twap_sim[0]), "Mean TWAP market impact:", np.mean(twap_sim[1]))

Mean TWAP slippage: -0.897435897435883 Mean TWAP market impact: 7.109024321022359e-06

In [76]:
vwap_sim = simulate_benchmark.simulate_strategy(vwap_trades,  preferred_timeframe=390)

In [77]:
print("Mean VWAP slippage:", np.mean(vwap_sim[0]), "Mean VWAP market impact:", np.mean(vwap_sim[1]))

Mean VWAP slippage: -0.6698171936876968 Mean VWAP market impact: 6.141669285962473e-06

In [ ]:
# pip install -U "ray[rllib]"

In [ ]:
# from ray.rllib.algorithms.dqn.dqn import DQNConfig

# config = (
#     DQNConfig()
#     .environment("Python 3")
#     .training(replay_buffer_config={
#         "type": "PrioritizedEpisodeReplayBuffer",
#         "capacity": 60000,
#         "alpha": 0.5,
#         "beta": 0.5,
#     })
#     .env_runners(num_env_runners=1)
# )
# algo = config.build()
# algo.train()
# algo.stop()

In [ ]:
data_aapl.info()

In [ ]:
modeling_data = data_aapl[['timestamp', 'bid_price_1', 'bid_size_1', 'open', 'high', 'low', 'close', 'volume']]

In [1]:
modeling_data = modeling_data.rename(columns={'bid_price_1': 'initial_price',
                                             'bid_size_1': 'initial_size'})

NameError: name 'modeling_data' is not defined

In [70]:
modeling_data

                      timestamp     open     high     low    close    volume
78373 2024-07-01 13:30:00+00:00  212.090  212.520  211.92  212.440  881677.0
78374 2024-07-01 13:31:00+00:00  212.450  213.085  212.35  212.995  173504.0
78375 2024-07-01 13:32:00+00:00  212.995  213.070  212.61  212.920   81464.0
78376 2024-07-01 13:33:00+00:00  212.950  213.260  212.55  213.170   68896.0
78377 2024-07-01 13:34:00+00:00  213.190  213.480  213.09  213.340   58383.0
...                         ...      ...      ...     ...      ...       ...
95498 2024-08-30 19:54:00+00:00  229.370  229.370  228.71  229.080  216299.0
95499 2024-08-30 19:55:00+00:00  229.060  229.200  228.65  229.000  252312.0
95500 2024-08-30 19:56:00+00:00  229.000  229.010  228.93  229.000  107179.0
95501 2024-08-30 19:57:00+00:00  228.990  229.000  228.97  229.000  137186.0
95502 2024-08-30 19:58:00+00:00  228.995  229.000  228.72  228.970  270532.0

[17093 rows x 6 columns]

In [75]:
class QLearningTrader:
    def __init__(self, num_actions, num_features, learning_rate, discount_factor, exploration_prob):
        self.num_actions = num_actions
        self.num_features = num_features
        self.learning_rate = learning_rate
        self.discount_factor = discount_factor
        self.exploration_prob = exploration_prob

        # Initialize Q-table with zeros
        self.q_table = np.zeros((num_actions, num_features))

        # Initialize state and action
        self.current_state = None
        self.current_action = None

    def choose_action(self, state):
        # Exploration-exploitation trade-off
        if np.random.uniform(0, 1) < self.exploration_prob:
            return np.random.choice(self.num_actions)  # Explore
        else:
            feature_index = np.argmax(state)
            return np.argmax(self.q_table[:, feature_index])  # Exploit

    def take_action(self, action, reward):
        # Update Q-table based on the observed reward
        if self.current_action is not None:
            feature_index = np.argmax(self.current_state)
            current_q_value = self.q_table[self.current_action, feature_index]
            new_q_value = (1 - self.learning_rate) * current_q_value + \
                           self.learning_rate * (reward + self.discount_factor * np.max(self.q_table[:, feature_index]))
            self.q_table[self.current_action, feature_index] = new_q_value

        # Update current state and action
        self.current_state = None
        self.current_action = action

    def observe_real_time_data(self, data):
        # Fetch real-time data
#         real_time_data = fetch_real_time_data(data)

        # Extract features from real-time data
        self.current_state = np.array([data['open'], data['high'],
                                       data['low'], data['close'],
                                       data['volume']])

    def observe_next_state(self, data):
        # Update the current state with the observed next state
        self.current_state = fetch_real_time_data(data)

# def fetch_real_time_data(identifier):
#     source = 'nasdaq_basic'
#     response = intrinio.SecurityApi().get_security_realtime_price(identifier, source=source)

#     return {
#         'open': response.open_price,
#         'high': response.high_price,
#         'low': response.low_price,
#         'close': response.last_price,
#         'volume': response.last_size
#     }

def calculate_reward(action, current_close, next_close):
#     if action == 0:  # Buy
#         return 1.0 if next_close > current_close else -1.0
    if action == 1:  # Sell
        return 1.0 if next_close < current_close else -1.0
    else:  # Hold
        return 1.0 if next_close > current_close else -1.0 if next_close < current_close else 0.0

def calculate_profit_loss(initial_balance, suggested_action, current_close, next_close, quantity):
#     if suggested_action == "Buy":
#         return (next_close - current_close) * quantity
    if suggested_action == "Sell":
        return (current_close - next_close) * quantity
    else:  # Hold
        return 0.0

def calculate_final_profit(data, initial_balance, num_iterations, learning_rate, discount_factor, exploration_prob):
    num_actions = 3
    num_features = 5
    q_trader = QLearningTrader(num_actions, num_features, learning_rate, discount_factor, exploration_prob)

    for i in range(num_iterations):
        for idx in range(len(data)):
            action = q_trader.choose_action(q_trader.current_state)
            shares = data.iloc[idx]['volume']
            # reward = self.compute_components(alpha, data, shares)
#             reward = np.array([data.iloc[idx]['slippage'], data.iloc[idx]['market_impact']])
            reward = calculate_reward(action, current_close, next_close)
            slippage.append(reward[0])
            market_impact.append(reward[1])
            shares_traded.append(shares)
            rewards.append(reward)
#         q_trader.observe_real_time_data(data)

#         action = q_trader.choose_action(q_trader.current_state)
#         current_close = q_trader.current_state[3]

# #         time.sleep(1)  # Introduce a delay before fetching the next real-time data

#         q_trader.observe_next_state(data)
#         next_close = q_trader.current_state['close']

#         reward = calculate_reward(action, current_close, next_close)
#         q_trader.take_action(action, reward)
        

    # Fetch real-time data just after the last iteration
    final_real_time_data = fetch_real_time_data(data)

    # Get the final suggested action based on the last state in the Q-table
    final_suggested_action = ["Sell", "Hold"][np.argmax(q_trader.q_table[:, np.argmax(q_trader.current_state)])]

    # Calculate profit based on the final suggested action
    final_profit = calculate_profit_loss(initial_balance, final_suggested_action, current_close, final_real_time_data['close'], quantity)

    print(f"Final Suggested Action: {final_suggested_action}, Final Profit: {final_profit}")

In [76]:
# security_identifier = 'AAPL'
alpha = 4.439584265535017e-06 
calculate_final_profit(modeling_data, 
                       initial_balance = 1000, 
                       volume = modeling_data.volume, 
                       num_iterations = 180, 
                       learning_rate = alpha, 
                       discount_factor = 0.9, 
                       exploration_prob = 0.2)

IndexError: index 69362 is out of bounds for axis 1 with size 5

In [ ]:
import keras
from keras.models import Sequential
from keras.models import load_model
from keras.layers import Dense
from keras.optimizers import Adam
from IPython.core.debugger import set_trace

import numpy as np
import random
from collections import deque

class Agent:
    def __init__(self, state_size, is_eval=False, model_name=""):
        #State size depends and is equal to the the window size, n previous days
        self.state_size = state_size # normalized previous days, 
        self.action_size = 3 # sit, buy, sell
        self.memory = deque(maxlen=1000)
        self.inventory = []
        self.model_name = model_name
        self.is_eval = is_eval

        self.gamma = 0.95
        self.epsilon = 1.0
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        #self.epsilon_decay = 0.9
        
        #self.model = self._model()

        self.model = load_model(model_name) if is_eval else self._model()
        
    def act(self, state): 
        #If it is test and self.epsilon is still very high, once the epsilon become low, there are no random
        #actions suggested.
        if not self.is_eval and random.random() <= self.epsilon:
            return random.randrange(self.action_size)        
        options = self.model.predict(state)
        #set_trace()
        #action is based on the action that has the highest value from the q-value function.
        return np.argmax(options[0])

    def expReplay(self, batch_size):
        mini_batch = []
        l = len(self.memory)
        for i in range(l - batch_size + 1, l):
            mini_batch.append(self.memory[i])
        
        # the memory during the training phase. 
        for state, action, reward, next_state, done in mini_batch:
            target = reward # reward or Q at time t    
            #update the Q table based on Q table equation
            #set_trace()
            if not done:
                #set_trace()
                #max of the array of the predicted. 
                target = reward + self.gamma * np.amax(self.model.predict(next_state)[0])     
                
            # Q-value of the state currently from the table    
            target_f = self.model.predict(state)
            # Update the output Q table for the given action in the table     
            target_f[0][action] = target
            #train and fit the model where state is X and target_f is Y, where the target is updated. 
            self.model.fit(state, target_f, epochs=1, verbose=0)
        
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

In [ ]:

def getState(data, t, n):    
    d = t - n + 1
    block = data[d:t + 1] if d >= 0 else -d * [data[0]] + data[0:t + 1] # pad with t0
    #block is which is the for [1283.27002, 1283.27002]
    res = []
    for i in range(n - 1):
        res.append(sigmoid(block[i + 1] - block[i]))
    return np.array([res])

In [ ]:
window_size = 1
agent = Agent(window_size)
# data = X_train
l = len(data) - 2
# batch_size = 32
# #An episode represents a complete pass over the data.
# episode_count = 10

In [ ]:
#initialize Q table

#define potential actions (sell, sit)

#Q-learning fxn:
#for each day, get current state
#define probability of the different actions (30% of the time random, 70% based on current state)
#get reward
    #if hold and there IS inventory currently available: reward is the current price - prev. price
    #if sell but no inventory: negative reward (-100)
    #if sell and is inventory: reward = current price  - first bought price

In [ ]:
class Q_learning:
    
    def __init__(self, data):
        """
        Initializes the Benchmark class with provided market data.

        Parameters:
        data (DataFrame): A DataFrame containing market data, including top 5 bid prices and sizes. (Use bid_ask_ohlcv_data)
        """
        # Use data with top 5 bid prices and sizes for benchmarking
        self.data = data


    def get_vwap_trades(self, data, initial_inventory, preferred_timeframe=390):
        """
        Generates a trade schedule based on the Volume-Weighted Average Price (VWAP) strategy.

        Parameters:
        data (DataFrame): The input data containing timestamps, closing prices, and volumes for each time step.
        initial_inventory (int): The total number of shares to be sold over the preferred timeframe.
        preferred_timeframe (int): The total number of time steps (default is 390, representing a full trading day).

        Returns:
        DataFrame: A DataFrame containing the VWAP trades with timestamps, price, shares sold, and remaining inventory.
        """
        total_volume = data['volume'].sum()
        total_steps = len(data)
        remaining_inventory = initial_inventory
        trades = []
        for step in range(min(total_steps, preferred_timeframe)):
            volume_at_step = data['volume'].iloc[step]
            size_of_slice = (volume_at_step / total_volume) * initial_inventory
            size_of_slice = min(size_of_slice, remaining_inventory)
            remaining_inventory -= int(np.ceil(size_of_slice))
            trade = {
                'timestamp': data.iloc[step]['timestamp'],
                'step': step,
                'price': data.iloc[step]['close'],
                'shares': size_of_slice,
                'inventory': remaining_inventory,
            }
            trades.append(trade)
        return pd.DataFrame(trades)
       
        
        def calculate_q(self, idx, shares):
      
#         # Assumes you have best 5 bid prices and sizes in your dataset
#         bid_prices = [self.data[f'bid_price_{i}'] for i in range(1,6)]
#         bid_sizes = [self.data[f'bid_size_{i}'] for i in range(1,6)]
#         cumsum = 0
#         for idx, size in enumerate(bid_sizes):
#             cumsum += size
#             if cumsum >= shares:
#                 break
        
#         return np.sum(bid_prices[:idx+1] * bid_sizes[:idx+1]) / np.sum(bid_sizes[:idx+1])

    def compute_components(self, alpha, shares, idx):
        """
        Computes the transaction cost components such as slippage and market impact for a given trade.

        Parameters:
        alpha (float): A scaling factor for market impact (determined empirically or based on research).
        shares (int): The number of shares being traded at the current step.
        idx (int): The index of the current step in the market data.

        Returns:
        array: A NumPy array containing the slippage and market impact for the given trade.
        """
        actual_price = self.calculate_vwap(idx, shares)
        Slippage = (self.data['bid_price_1'] - actual_price) * shares  # Assumes bid_price is in your dataset
        Market_Impact = alpha * np.sqrt(shares)
        return np.array([Slippage, Market_Impact])
    
    def simulate_Q_learning(self, data, preferred_timeframe):
        """
        Simulates a trading strategy and calculates various transaction cost components.

        Parameters:
        trades (DataFrame): A DataFrame where each row contains 'shares' and 'action' for each trade.
        data (DataFrame): Market data including bid prices and volumes.
        preferred_timeframe (int): The total number of time steps over which the strategy is simulated.

        Returns:
        tuple: A tuple containing lists of slippage, market impact.
        """
        
        # Initialize result lists
        slippage = []
        market_impact = []
        alpha = 4.439584265535017e-06 
        rewards = []
        shares_traded = []

        # Simulate the strategy
        for idx in range(len(data)):
            shares = data.iloc[idx]['volume']
            # reward = self.compute_components(alpha, data, shares)
            reward = np.array([data.iloc[idx]['slippage'], data.iloc[idx]['market_impact']])
            slippage.append(reward[0])
            market_impact.append(reward[1])
            shares_traded.append(shares)
            rewards.append(reward)

        return slippage, market_impact

In [79]:
#need to initialize a matrix of size (n observations)X(n actions)
# we are only looking at the seller action for this, so there are only 2 actions available (sell or hold)
#the number of observations is number of data point in the time frame (390 for 1 trading day)

#Initialize the Q-table to 0
Q_table = np.zeros((390,2))
print(Q_table)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

In [80]:
#next, define the different parameters necessary
#for MDP, need to define states, actions, transition probability, reward function, and discount factor

#states:
S = 390

#Actions:
A = 2

#Transition Probability:
#probability of changing states, given action a
P = 0.01

# Reward Function
# for comparison to benchmarks, want to minimize slippage and market impact as "rewards"
# R = 


#discount factor:
#if closer to 1, agent will prioritize future reward
#if closer to 0, agent will prioritize immediate reward
gamma = .99

In [ ]:
for s in range(S):
#     #we initialize the first state of the episode
#     current_state = env.reset()
#     done = False
    
    #sum the rewards that the agent gets from the environment
    total_reward = 0
    
    for i in range(max_iter_state): 
        # we sample a float from a uniform distribution over 0 and 1
        # if the sampled flaot is less than the exploration proba
        #     the agent selects arandom action
        # else
        #     he exploits his knowledge using the bellman equation 
        
        if np.random.uniform(0,1) < exploration_proba:
            action = env.A.sample()
        else:
            action = np.argmax(Q_table[current_state,:])
        
        # The environment runs the chosen action and returns
        # the next state, a reward and true if the epiosed is ended.
        next_state, reward, done, _ = env.step(action)
        
        # We update our Q-table using the Q-learning iteration
        Q_table[current_state, action] = (1-lr) * Q_table[current_state, action] +lr*(reward + gamma*max(Q_table[next_state,:]))
        total_episode_reward = total_episode_reward + reward
        # If the episode is finished, we leave the for loop
        if done:
            break
        current_state = next_state
    #We update the exploration proba using exponential decay formula 
    exploration_proba = max(min_exploration_proba, np.exp(-exploration_decreasing_decay*e))
    rewards_per_episode.append(total_episode_reward)

In [ ]:
# params = params._replace(action_size=env.action_space.n)
# params = params._replace(state_size=env.observation_space.n)
# print(f"Action size: {params.action_size}")
# print(f"State size: {params.state_size}")


class Qlearning:
    def __init__(self, learning_rate, gamma, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.learning_rate = learning_rate
        self.gamma = gamma
        self.reset_qtable()

    def update(self, state, action, reward, new_state):
        """Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]"""
        delta = (
            reward
            + self.gamma * np.max(self.qtable[new_state, :])
            - self.qtable[state, action]
        )
        q_update = self.qtable[state, action] + self.learning_rate * delta
        return q_update

    def reset_qtable(self):
        """Reset the Q-table."""
        self.qtable = np.zeros((self.state_size, self.action_size))


class EpsilonGreedy:
    def __init__(self, epsilon):
        self.epsilon = epsilon

    def choose_action(self, action_space, state, qtable):
        """Choose an action `a` in the current world state (s)."""
        # First we randomize a number
        explor_exploit_tradeoff = rng.uniform(0, 1)

        # Exploration
        if explor_exploit_tradeoff < self.epsilon:
            action = action_space.sample()

        # Exploitation (taking the biggest Q-value for this state)
        else:
            # Break ties randomly
            # Find the indices where the Q-value equals the maximum value
            # Choose a random action from the indices where the Q-value is maximum
            max_ids = np.where(qtable[state, :] == max(qtable[state, :]))[0]
            action = rng.choice(max_ids)
        return action